services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_chat
    volumes:
      - "./docker:/docker-entrypoint-initdb.d" #garantir que execute scripts SQL na pasta designada automaticamente ao iniciar o container.
